version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    prod-dependencies:
      dependency-type: "production"
      update-types:
        - "minor"
        - "patch"
    dev-dependencies:
      dependency-type: "development"
      update-types:
        - "minor"
        - "patch"
